
[settings]

	[settings.category]
		shorten_prefix = true

[parakeet]

	[parakeet.category]
		parakeet_message = ""

[riftstalker]
	auto_ice = false

	[riftstalker.auto_use]
		auto_ice = false

	[riftstalker.automation]
		auto_ice = false

	[riftstalker.impel]
		rotate = false
		auto_impel_ = false
		auto_impel = false

	[riftstalker.category]
		auto_ice = false
		auto_impel = true

	[riftstalker.auto_impel]
		toggle_auto_impel = false
		no_rotate = false

